#!/usr/bin/env bash
#This script Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program should pause for 2 seconds
if [ "$1" = start ]
then
    sudo -b ./manage_my_process
    pgrep -if  ./manage_my_process | grep sudo |cut -d " " -f 1 > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" = stop ]
then
     pkill -f ./manage_my_process
     rm -r /var/run/my_process.pid
     sudo  -b ./manage_my_process
     pgrep -lf ./manage_my_process | cut -d " " -f 1 > /var/run/my_process.pid
     echo "manage_my_process stopped"
elif [ "$1" = restart ]
then
     pkill -f ./manage_my_process
     rm /var/run/my_process.pid
     sudo  -b ./manage_my_process
     pgrep -lf ./manage_my_process | cut -d " " -f 1 > /var/run/my_process.pid
     echo "manage_my_process restarted"
else
     echo  "Usage: manage_my_process {start|stop|restart}"
fi

