#!/usr/bin/env bash
# This script uses the previous command and displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
